# yml文件不能使用制表符空格tab，只能用普通空间表示缩进
server:
  port: 8000

spring:
   application:
      name: server

eureka:
   client:
      service-url:
         defaultZone: http://127.0.0.1:8000
      registerWithEureka: false
      fetchRegistry: false
       