# yml文件不能使用制表符空格tab，只能用普通空间表示缩进
server:
  port: 8001


# 定义当前服务名
spring:
   application:
      name: user
# 配置Eureka 服务器的地址
eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:8000/eureka     
