# yml文件不能使用制表符空格tab，只能用普通空间表示缩进
server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/lxblog?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: a
    driver-class-name: com.mysql.jdbc.Driver
    
